eureka:
  instance:
    hostname: service-registry #${vcap.application.uris[0]:service-registry}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8080/eureka

security:
  saml2:
    metadata-url: https://dev-920658.okta.com/app/exkr22uaciecxFpYR4x6/sso/saml/metadata      
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rdsdb.ceoijrvepzdr.us-east-2.rds.amazonaws.com:3306/srt
    username: rdsdb
    password: rdsdb12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      #naming:
       # implicit-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update    
      use-new-id-generator-mappings: false
  servlet:
   multipart:
    max-file-size: 100MB
    max-request-size: 100MB
      
management:
  aws:
    access:
    ## AWS Account Config (isRemoteAccessAWS: true/false or yes/no)
      isRemoteAccessAWS: true
      awsAccessKeyId: AKIAJDZOZ2APJTKFGDMA
      awsSecretKey: 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
      region: us-east-2
    csv:
      report:
        bucketname: srt-csv-terminal-report    
        filetype: .csv
    tgz:
      fileupload:
        bucketname: s3-tgz-bucket        
  application:
    url: https://localhost:8070/saml/login?disco=true&idp=http%3A%2F%2Fwww.okta.com%2Fexkr22uaciecxFpYR4x6
  bitbucket:
    url: 'https://bitbucket.verifone.com:8443/scm/~grahams3/global_repair.git'
  swagger:
    contact:
        name: 'Service Repair Application'
        email: 'mithileshv1@verifone.com'
        url: ${management.application.url}
    externaldocs:
        git:
          url: ${management.bitbucket.url} 
    api:
      info:
        termsOfService: 'Terms of service for using Service Repair Api' #'https://service-repair/terms'